include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint

custom_lints_template:
  avoid_banned_filenames:
    entries:
     - "bad[^\\.]*.dart"
  avoid_hardcoded_strings:
    minimum_length: 4
    severity: warning