name: boolean_lints

packages:
  - packages/**
  - example/**

scripts:
  # Custom lint is only applied to the packages and not the root app because of a dependency conflict with `integration_test` and `melos`
  pub:
    run: melos run dart:pkg --no-select && melos run flutter:pkg --no-select
    description: Run `dart pub get` in all packages.
  
  dart:pkg:
    run: dart pub get
    exec:
      failFast: true
      concurrency: 1
    description: Run `dart pub get` in the selected package.
    packageFilters:
      noDependsOn: flutter
  
  flutter:pkg:
    run: flutter pub get
    exec:
      failFast: true
      concurrency: 1
    description: Run `flutter pub get` in the selected package.
    packageFilters:
      dependsOn: flutter

  analyze:
    run: melos run analyze:pkg --no-select && melos run custom_lint
    description: Run `dart analyze` in all packages.

  analyze:pkg:
    run: dart analyze --fatal-infos lib
    exec: 
      failFast: true
      concurrency: 1
    description: Run `dart analyze` on all packages.

  custom_lint:
    run: melos run custom_lint:pkg --no-select
    description: Run `dart run custom_lint` in all packages with custom lints.

  custom_lint:pkg:
    run: dart run custom_lint
    exec:
      failFast: true
      concurrency: 1
    description: Run `dart run custom_lint` in the selected package.
    packageFilters:
      dependsOn: custom_lint

  upgrade:
    run: |
      dart pub upgrade
      melos run upgrade:pkg --no-select
    description: Run `dart pub upgrade` in all packages.

  upgrade:pkg:
    run: dart pub upgrade
    exec:
      failFast: true
    description: Run `dart pub upgrade` in the selected package.

  upgrade-major:
    run: |
      dart pub upgrade
      melos run upgrade:pkg --no-select
    description: Run `dart pub upgrade --major-versions` in all packages.

  upgrade-major:pkg:
    run: dart pub upgrade --major-versions
    exec:
      failFast: true
    description: Run `dart pub upgrade --major-versions` in the selected package.

  format:
    exec: dart format .
    description: Run `dart format` in all packages.

  fix:
    exec: dart fix --apply
    description: Run `dart fix --apply` in all packages.

  verify_format:
    run: dart format --output=none --set-exit-if-changed .
    exec: 
      failFast: true
    description: Verify formatting was applied.
