name: custom_lints_template
description: custom_lints_template is a developer tool, designed to help stop common issue and simplify repetetive tasks. It adds various warnings with quick fixes and refactoring options.
version: 1.0.0
repository: https://github.com/getBoolean/custom_lints_template
issue_tracker: https://github.com/getBoolean/custom_lints_template/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  analyzer_plugin: ^0.11.2
  collection: ^1.16.0
  custom_lint_builder: ">=0.4.0 <0.6.0"
  dart_mappable: ">=3.0.1 <5.0.0"
  meta: ^1.7.0
  path: ^1.8.1
  pub_semver: ^2.1.4
  source_span: ^1.8.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: any
  build_verify: ^3.1.0
  dart_mappable_builder: ">=3.0.2 <5.0.0"
  test: ^1.24.3
# custom_lints_template:
#   avoid_banned_filenames:
#     entries:
#      - "bad[\\.]*.dart"
