name: CI
on:
  push:
    branches:
      - main
      - release
      - feature/*
      - fix/*
      - chore/*
      - dependabot/*

env:
  FLUTTER_CHANNEL: "stable"
  FLUTTER_VERSION: "any"

jobs:
  test:
    name: Run dart analyze and custom_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          architecture: x64

      - name: Check Flutter Version
        run: flutter --version

      - name: Activate Melos
        run: dart pub global activate melos ^3.1.1

      - name: Bootstrap Melos
        run: dart run melos bootstrap
      
      - name: Verify Formatting
        run: melos run verify_format

      - name: Analyze
        run: melos run analyze
      
      - name: Run Tests
        run: dart test
