name: CI
on:
  push:
    branches:
      - main
      - release
      - feature/*
      - template
  pull_request:
    branches:
      - main
      - release
      - feature/*
      - template


jobs:
  test:
    name: Run dart analyze and custom_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      
      - name: Get Packages
        run: |
          dart pub get
          dart pub get -C example/random
          dart pub get -C example/random_clone

      - name: Verify Formatting
        run: dart format --set-exit-if-changed .

      - name: Run Dart Analyze
        run: dart analyze --fatal-warnings
      
      - name: Run Tests
        run: dart test

      - name: Run Custom Lints
        run: |
          cd example/random
          dart run custom_lint
          cd ../..

          cd example/random_clone
          dart run custom_lint
          cd ../..
